const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export { GET_TODOS_REQUEST, GET_TODOS_SUCCESS, GET_TODOS_FAILURE };
